let places = ["Turkey", "Malaysia", "Argentina", "Europe", "Canada"];
console.log(places);
let sortPlaces = [...places].sort();
console.log(sortPlaces);
console.log(places);
let revPlaces = [...sortPlaces].reverse();
console.log(revPlaces);
console.log(places);
let revMainPlaces = [...places].reverse();
console.log(revMainPlaces);
console.log(places);
